# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30, verbose_name='\u73ed\u7ea7\uff1a')),
            ],
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30, verbose_name='\u59d3\u540d\uff1a')),
                ('password', models.CharField(max_length=30)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Clazz')),
            ],
        ),
    ]
